export const ERRORS = {
    credits: "Invalid email or password",
    unknown: "Unknown error",
    emailFormat: "Entered value does not match email format",
    passwordLength: "Enter password (3 to 32 characters)",
    fieldRequired: "This field is required",
    nameLength: "Name length must not exceed 100 characters",
    usernameLength: "Username length must not exceed 32 characters",
    usernameFormat: "Username must contain only alphabetical characters and numbers",
    nameFormat: "Name must contain only alphabetical characters",
    maxLinks: "You can't add more than 10 links to your profile",
    linkNameLength: "Link name length must not exceed 32 characters",
    linkNameFormat: "Link Name must contain only alphabetical characters and numbers",
    linkURLLength: "URL length must not exceed 100 characters",
    linkURLFormat: "Enter a valid URL",
};